title: Regan’s Senior Research Project
description: The objective of my project is to see which AI is the best for determining whether an email is a phishing email or not. I will use three popular AIs and a prompt that guides them into their decision, as well as providing a result on whether an email is phishing or not.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
